# Section
[GateServer]
# Section 下的键值对
Port = 8080
[VerifyServer]
Host = 127.0.0.1
Port = 50051
[Redis]
Host = 127.0.0.1
Port = 6379
Password = 123456
[Mysql]
Host = 127.0.0.1
Port = 3308
Password = 123456
User = root
Schema = chat
[StatusServer]
Host = 127.0.0.1
Port = 50052
[SelfServer]
Name = chatServer1
Host = 0.0.0.0
Port =8090
RPCPort = 50055
# 对端server列表
[PeerServer]
Servers = chatServer2
[chatServer2]
Host = 127.0.01
Name = chatServer2
Port =50056